/* This file was generated by SableCC (http://www.sablecc.org/). */

package tesauro.node;

import tesauro.analysis.*;

@SuppressWarnings("nls")
public final class AAsLongAsIterationCmdNoShortIct extends PIterationCmdNoShortIct
{
    private PExp _cond_;
    private PCmdNoShortIct _cmdAa_;

    public AAsLongAsIterationCmdNoShortIct()
    {
        // Constructor
    }

    public AAsLongAsIterationCmdNoShortIct(
        @SuppressWarnings("hiding") PExp _cond_,
        @SuppressWarnings("hiding") PCmdNoShortIct _cmdAa_)
    {
        // Constructor
        setCond(_cond_);

        setCmdAa(_cmdAa_);

    }

    @Override
    public Object clone()
    {
        return new AAsLongAsIterationCmdNoShortIct(
            cloneNode(this._cond_),
            cloneNode(this._cmdAa_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAsLongAsIterationCmdNoShortIct(this);
    }

    public PExp getCond()
    {
        return this._cond_;
    }

    public void setCond(PExp node)
    {
        if(this._cond_ != null)
        {
            this._cond_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond_ = node;
    }

    public PCmdNoShortIct getCmdAa()
    {
        return this._cmdAa_;
    }

    public void setCmdAa(PCmdNoShortIct node)
    {
        if(this._cmdAa_ != null)
        {
            this._cmdAa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cmdAa_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond_)
            + toString(this._cmdAa_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond_ == child)
        {
            this._cond_ = null;
            return;
        }

        if(this._cmdAa_ == child)
        {
            this._cmdAa_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond_ == oldChild)
        {
            setCond((PExp) newChild);
            return;
        }

        if(this._cmdAa_ == oldChild)
        {
            setCmdAa((PCmdNoShortIct) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
