/* This file was generated by SableCC (http://www.sablecc.org/). */

package tesauro.node;

import java.util.*;
import tesauro.analysis.*;

@SuppressWarnings("nls")
public final class ACompostoTipo extends PTipo
{
    private PTipo _tipo_;
    private TVector _vector_;
    private final LinkedList<PExp> _vec_ = new LinkedList<PExp>();

    public ACompostoTipo()
    {
        // Constructor
    }

    public ACompostoTipo(
        @SuppressWarnings("hiding") PTipo _tipo_,
        @SuppressWarnings("hiding") TVector _vector_,
        @SuppressWarnings("hiding") List<?> _vec_)
    {
        // Constructor
        setTipo(_tipo_);

        setVector(_vector_);

        setVec(_vec_);

    }

    @Override
    public Object clone()
    {
        return new ACompostoTipo(
            cloneNode(this._tipo_),
            cloneNode(this._vector_),
            cloneList(this._vec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompostoTipo(this);
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TVector getVector()
    {
        return this._vector_;
    }

    public void setVector(TVector node)
    {
        if(this._vector_ != null)
        {
            this._vector_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vector_ = node;
    }

    public LinkedList<PExp> getVec()
    {
        return this._vec_;
    }

    public void setVec(List<?> list)
    {
        for(PExp e : this._vec_)
        {
            e.parent(null);
        }
        this._vec_.clear();

        for(Object obj_e : list)
        {
            PExp e = (PExp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._vec_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipo_)
            + toString(this._vector_)
            + toString(this._vec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._vector_ == child)
        {
            this._vector_ = null;
            return;
        }

        if(this._vec_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        if(this._vector_ == oldChild)
        {
            setVector((TVector) newChild);
            return;
        }

        for(ListIterator<PExp> i = this._vec_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
