/* This file was generated by SableCC (http://www.sablecc.org/). */

package tesauro.node;

import tesauro.analysis.*;

@SuppressWarnings("nls")
public final class AIctDoElseNoShortIct extends PIctDoElseNoShortIct
{
    private PExp _exp_;
    private PCmdNoShortIct _cmd1_;
    private PCmdNoShortIct _cmd2_;

    public AIctDoElseNoShortIct()
    {
        // Constructor
    }

    public AIctDoElseNoShortIct(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PCmdNoShortIct _cmd1_,
        @SuppressWarnings("hiding") PCmdNoShortIct _cmd2_)
    {
        // Constructor
        setExp(_exp_);

        setCmd1(_cmd1_);

        setCmd2(_cmd2_);

    }

    @Override
    public Object clone()
    {
        return new AIctDoElseNoShortIct(
            cloneNode(this._exp_),
            cloneNode(this._cmd1_),
            cloneNode(this._cmd2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIctDoElseNoShortIct(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PCmdNoShortIct getCmd1()
    {
        return this._cmd1_;
    }

    public void setCmd1(PCmdNoShortIct node)
    {
        if(this._cmd1_ != null)
        {
            this._cmd1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cmd1_ = node;
    }

    public PCmdNoShortIct getCmd2()
    {
        return this._cmd2_;
    }

    public void setCmd2(PCmdNoShortIct node)
    {
        if(this._cmd2_ != null)
        {
            this._cmd2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cmd2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._cmd1_)
            + toString(this._cmd2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._cmd1_ == child)
        {
            this._cmd1_ = null;
            return;
        }

        if(this._cmd2_ == child)
        {
            this._cmd2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._cmd1_ == oldChild)
        {
            setCmd1((PCmdNoShortIct) newChild);
            return;
        }

        if(this._cmd2_ == oldChild)
        {
            setCmd2((PCmdNoShortIct) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
