/* This file was generated by SableCC (http://www.sablecc.org/). */

package tesauro.node;

import tesauro.analysis.*;

@SuppressWarnings("nls")
public final class AIctDoElse extends PIctDoElse
{
    private PExp _exp_;
    private PCmdNoShortIct _cmdNoShortIct_;
    private PCmd _cmd_;

    public AIctDoElse()
    {
        // Constructor
    }

    public AIctDoElse(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PCmdNoShortIct _cmdNoShortIct_,
        @SuppressWarnings("hiding") PCmd _cmd_)
    {
        // Constructor
        setExp(_exp_);

        setCmdNoShortIct(_cmdNoShortIct_);

        setCmd(_cmd_);

    }

    @Override
    public Object clone()
    {
        return new AIctDoElse(
            cloneNode(this._exp_),
            cloneNode(this._cmdNoShortIct_),
            cloneNode(this._cmd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIctDoElse(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PCmdNoShortIct getCmdNoShortIct()
    {
        return this._cmdNoShortIct_;
    }

    public void setCmdNoShortIct(PCmdNoShortIct node)
    {
        if(this._cmdNoShortIct_ != null)
        {
            this._cmdNoShortIct_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cmdNoShortIct_ = node;
    }

    public PCmd getCmd()
    {
        return this._cmd_;
    }

    public void setCmd(PCmd node)
    {
        if(this._cmd_ != null)
        {
            this._cmd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cmd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._cmdNoShortIct_)
            + toString(this._cmd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._cmdNoShortIct_ == child)
        {
            this._cmdNoShortIct_ = null;
            return;
        }

        if(this._cmd_ == child)
        {
            this._cmd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._cmdNoShortIct_ == oldChild)
        {
            setCmdNoShortIct((PCmdNoShortIct) newChild);
            return;
        }

        if(this._cmd_ == oldChild)
        {
            setCmd((PCmd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
