/* This file was generated by SableCC (http://www.sablecc.org/). */

package tesauro.node;

import tesauro.analysis.*;

@SuppressWarnings("nls")
public final class AIctDoElseNoIfCmdNoShortIct extends PCmdNoShortIct
{
    private PIctDoElseNoShortIct _ictDoElseNoShortIct_;

    public AIctDoElseNoIfCmdNoShortIct()
    {
        // Constructor
    }

    public AIctDoElseNoIfCmdNoShortIct(
        @SuppressWarnings("hiding") PIctDoElseNoShortIct _ictDoElseNoShortIct_)
    {
        // Constructor
        setIctDoElseNoShortIct(_ictDoElseNoShortIct_);

    }

    @Override
    public Object clone()
    {
        return new AIctDoElseNoIfCmdNoShortIct(
            cloneNode(this._ictDoElseNoShortIct_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIctDoElseNoIfCmdNoShortIct(this);
    }

    public PIctDoElseNoShortIct getIctDoElseNoShortIct()
    {
        return this._ictDoElseNoShortIct_;
    }

    public void setIctDoElseNoShortIct(PIctDoElseNoShortIct node)
    {
        if(this._ictDoElseNoShortIct_ != null)
        {
            this._ictDoElseNoShortIct_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ictDoElseNoShortIct_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ictDoElseNoShortIct_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ictDoElseNoShortIct_ == child)
        {
            this._ictDoElseNoShortIct_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ictDoElseNoShortIct_ == oldChild)
        {
            setIctDoElseNoShortIct((PIctDoElseNoShortIct) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
