/* This file was generated by SableCC (http://www.sablecc.org/). */

package tesauro.node;

import tesauro.analysis.*;

@SuppressWarnings("nls")
public final class AIntValExp extends PExp
{
    private TIntVal _intVal_;

    public AIntValExp()
    {
        // Constructor
    }

    public AIntValExp(
        @SuppressWarnings("hiding") TIntVal _intVal_)
    {
        // Constructor
        setIntVal(_intVal_);

    }

    @Override
    public Object clone()
    {
        return new AIntValExp(
            cloneNode(this._intVal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntValExp(this);
    }

    public TIntVal getIntVal()
    {
        return this._intVal_;
    }

    public void setIntVal(TIntVal node)
    {
        if(this._intVal_ != null)
        {
            this._intVal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intVal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._intVal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._intVal_ == child)
        {
            this._intVal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._intVal_ == oldChild)
        {
            setIntVal((TIntVal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
