/* This file was generated by SableCC (http://www.sablecc.org/). */

package tesauro.node;

import tesauro.analysis.*;

@SuppressWarnings("nls")
public final class AIterationCmdNoIfCmdNoShortIct extends PCmdNoShortIct
{
    private PIterationCmdNoShortIct _iterationCmdNoShortIct_;

    public AIterationCmdNoIfCmdNoShortIct()
    {
        // Constructor
    }

    public AIterationCmdNoIfCmdNoShortIct(
        @SuppressWarnings("hiding") PIterationCmdNoShortIct _iterationCmdNoShortIct_)
    {
        // Constructor
        setIterationCmdNoShortIct(_iterationCmdNoShortIct_);

    }

    @Override
    public Object clone()
    {
        return new AIterationCmdNoIfCmdNoShortIct(
            cloneNode(this._iterationCmdNoShortIct_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIterationCmdNoIfCmdNoShortIct(this);
    }

    public PIterationCmdNoShortIct getIterationCmdNoShortIct()
    {
        return this._iterationCmdNoShortIct_;
    }

    public void setIterationCmdNoShortIct(PIterationCmdNoShortIct node)
    {
        if(this._iterationCmdNoShortIct_ != null)
        {
            this._iterationCmdNoShortIct_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._iterationCmdNoShortIct_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._iterationCmdNoShortIct_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._iterationCmdNoShortIct_ == child)
        {
            this._iterationCmdNoShortIct_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._iterationCmdNoShortIct_ == oldChild)
        {
            setIterationCmdNoShortIct((PIterationCmdNoShortIct) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
