/* This file was generated by SableCC (http://www.sablecc.org/). */

package tesauro.node;

import java.util.*;
import tesauro.analysis.*;

@SuppressWarnings("nls")
public final class AShowCmdSemCmd extends PCmdSemCmd
{
    private final LinkedList<PExp> _lista_ = new LinkedList<PExp>();
    private PExp _exp_;

    public AShowCmdSemCmd()
    {
        // Constructor
    }

    public AShowCmdSemCmd(
        @SuppressWarnings("hiding") List<?> _lista_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setLista(_lista_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AShowCmdSemCmd(
            cloneList(this._lista_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAShowCmdSemCmd(this);
    }

    public LinkedList<PExp> getLista()
    {
        return this._lista_;
    }

    public void setLista(List<?> list)
    {
        for(PExp e : this._lista_)
        {
            e.parent(null);
        }
        this._lista_.clear();

        for(Object obj_e : list)
        {
            PExp e = (PExp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._lista_.add(e);
        }
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lista_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lista_.remove(child))
        {
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExp> i = this._lista_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
