/* This file was generated by SableCC (http://www.sablecc.org/). */

package tesauro.node;

public abstract class PExp extends Node
{
    protected String tipo;
    
    public String getTipo() {
    	return tipo;
    }
    public void setTipo(String tipo) {
    	this.tipo = tipo;
    }
}
