/* This file was generated by SableCC (http://www.sablecc.org/). */

package tesauro.node;

public abstract class PExp extends Node
{
    protected String tipo;
    protected PExp _left_;
    protected PExp _right_;
    protected PExp _valor_;
    protected int op_tipo = -1;
    protected int is_constant = -1;
    protected int is_init = -1;
    protected int is_vec = -1;
    /**
     * 0 - Relacional
     * 1 - Booleana
     * 2 - Aritmética
     */
    
    public String getTipo() {
    	return tipo;
    }
    public int getOp_tipo() {
		return op_tipo;
	}
	public void setOp_tipo(int op_tipo) {
		this.op_tipo = op_tipo;
	}
	public void setTipo(String tipo) {
    	this.tipo = tipo;
    }
	public PExp getLeft() {
		return _left_;
	}
	public void setLeft(PExp _left_) {
		this._left_ = _left_;
	}
	public PExp getRight() {
		return _right_;
	}
	public void setRight(PExp _right_) {
		this._right_ = _right_;
	}
	public PExp getValor() {
		return _valor_;
	}
	public void setValor(PExp _valor_) {
		this._valor_ = _valor_;
	}
	public void setIsConstant(int is_constant) {
		this.is_constant = is_constant;
	}
	public void setIsInit(int is_init) {
		this.is_init = is_init;
	}
	public int getIsInit() {
		return is_init;
	}
	public int getIsConstant() {
		return is_constant;
	}
	public void setIsVec(int is_vec) {
		this.is_vec = is_vec;
	}
	public int getIsVec() {
		return is_vec;
	}
    
}
