/* This file was generated by SableCC (http://www.sablecc.org/). */

package tesauro.node;

import tesauro.analysis.*;

@SuppressWarnings("nls")
public final class TInteger extends Token
{
    public TInteger()
    {
        super.setText("Integer");
    }

    public TInteger(int line, int pos)
    {
        super.setText("Integer");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInteger(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInteger(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInteger text.");
    }
}
